# Generated by Django 5.2.4 on 2025-08-06 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=30)),
                ('billed_amount', models.PositiveBigIntegerField()),
                ('paid_amount', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('Denied', 'Denied'), ('Under Review', 'Under Review'), ('Paid', 'Paid')], default='Under Review', max_length=12)),
                ('insurer_name', models.CharField(max_length=50)),
                ('discharge_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ClaimDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denial_reason', models.CharField(max_length=100)),
                ('cpt_codes', models.CharField(max_length=50)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.claim')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_review_flag', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.claim')),
            ],
        ),
    ]
